live_config_reload = true
import = [
  "~/.config/alacritty/themes/tomorrow_night_bright.toml",
  "~/.config/alacritty/themes/everforest_dark.toml",
]

[font]
normal = { family = "Moralerspace Argon HWNF", style = "Italic" }
bold = { family = "Moralerspace Argon HWNF", style = "Bold Italic" }
italic = { family = "Moralerspace Argon HWNF", style = "Italic" }
bold_italic = { family = "Moralerspace Argon HWNF", style = "Bold Italic" }
size = 14.0
offset = { x = 2, y = 2 }

[env]
term = "xterm-256color"

[colors]
vi_mode_cursor = { text = "#000000", cursor = "#FFBC5D" }

[window]
option_as_alt = "Both"
dimensions = { columns = 200, lines = 60 }
padding = { x = 8, y = 4 }
opacity = 1

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "v", mods = "Control", action = "ToggleViMode" },
  { key = "m", mods = "Control", chars = "=" },
  { key = "i", mods = "Control", chars = "-" },
  { key = "h", mods = "Command", action = "SelectPreviousTab" },
  { key = "l", mods = "Command", action = "SelectNextTab" },
]

[scrolling]
history = 100000

[cursor]
vi_mode_style = { shape = "Block", blinking = "Always" }
style = "Block"
