shell = "zsh"
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

# [plugins.zsh-vi-mode]
# github = "jeffreytse/zsh-vi-mode"
# apply = ["source"]

[plugins.dotfiles-defers]
local = "~/git/dotfiles/config/zsh"
use = ["{!sync,*}.zsh"]

# [plugins.dotfiles-sync]
# local = "~/git/dotfiles/config/zsh"
# use = ["sync.zsh"]
# apply = ["source"]
