keybinding:
  universal:
    prevItem: "k"
    nextItem: "j"
    scrollUpMain: "<up>"
    scrollDownMain: "<down>"
customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
os:
  editPreset: 'nvim'
